import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import NavBar from '@/components/Navbar';
import TopMenu from '@/components/TopMenu';
import AuthModalHost from '@/components/AuthModalHost';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'TOOLS',
  title: 'Rate My Tools',
  description: 'Generated by ics-software-engineering.github.io',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classString = `${inter.className} wrapper`;
  return (
    <html lang="en">
      <body className={classString}>
        <Providers>
          <TopMenu title={metadata.title as string} />
          <TopMenu title="TOOLS" />
          <AuthModalHost />
          {children}
        </Providers>
      </body>
    </html>
  );
}
