import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import TopMenu from '@/components/TopMenu';
import AuthModalHost from '@/components/AuthModalHost';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Rate My Tools',
  description: 'Generated by ics-software-engineering.github.io',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classString = `${inter.className} wrapper`;
  return (
    <html lang="en">
      <head>
        {/* Preload critical resources */}
        <link rel="preload" as="image" href="/RATEMY.png" />
        {/* DNS prefetch for external services */}
        <link rel="dns-prefetch" href="//api.github.com" />
      </head>
      <body className={classString}>
        <Providers>
          <TopMenu title="TOOLS" />
          <AuthModalHost />
          <main style={{ marginTop: '40px', backgroundColor: '#f9fafb' }}>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
